import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return json({ok:false,error:"missing_authorization"},401);const {data:u}=await db.auth.getUser(auth.slice(7));if(!u.user)return json({ok:false,error:"invalid_session"},401);
 const b=await req.json();const companyId=String(b.company_id||"");const channel=String(b.channel||"");if(!companyId||!["whatsapp","instagram"].includes(channel))return json({ok:false,error:"company_id_and_supported_channel_required"},400);
 const {data:p}=await db.from("profiles").select("company_id,role,is_platform_owner,can_view_settings,can_manage_team").eq("id",u.user.id).maybeSingle();if(!p||p.company_id!==companyId||!(p.is_platform_owner||p.role==="owner"||p.can_view_settings||p.can_manage_team))return json({ok:false,error:"forbidden"},403);
 const {data:i}=await db.from("integration_accounts").select("*").eq("company_id",companyId).eq("provider","meta").eq("channel",channel).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!i?.access_token)return json({ok:false,error:"integration_not_connected"},400);
 let id=String(i.external_account_id||"");let graph:any={};
 if(channel==="whatsapp"){const phone=String(i.metadata?.phone_number_id||id);const r=await fetch(`https://graph.facebook.com/v23.0/${phone}?fields=id,display_phone_number,verified_name&access_token=${encodeURIComponent(i.access_token)}`);graph=await r.json().catch(()=>({}));if(!r.ok||graph.error)return json({ok:false,error:"whatsapp_token_validation_failed",details:graph?.error?.message||`HTTP ${r.status}`},400);id=phone;}
 else{const r=await fetch(`https://graph.facebook.com/v23.0/${id}?fields=id,username,name&access_token=${encodeURIComponent(i.access_token)}`);graph=await r.json().catch(()=>({}));if(!r.ok||graph.error)return json({ok:false,error:"instagram_token_validation_failed",details:graph?.error?.message||`HTTP ${r.status}`},400);const sr=await fetch(`https://graph.facebook.com/v23.0/${id}/subscribed_apps?subscribed_fields=messages&access_token=${encodeURIComponent(i.access_token)}`,{method:"POST"});const so=await sr.json().catch(()=>({}));if(!sr.ok||so.error)return json({ok:false,error:"instagram_webhook_subscription_failed",details:so?.error?.message||`HTTP ${sr.status}`},400);graph.webhook_subscription=so;}
 const meta={...(i.metadata||{}),connection_status:"connected",last_validated_at:new Date().toISOString(),validated_account_id:id,webhook_url:"https://bbixzcaxlvotdhhqfatw.supabase.co/functions/v1/facebook-webhook-v2",webhook_verify_token:"botera_fb_webhook_2026"};
 if(channel==="whatsapp")meta.phone_number_id=id;
 const up=await db.from("integration_accounts").update({is_active:true,external_account_id:id,external_account_name:graph.display_phone_number||graph.verified_name||graph.username||graph.name||null,metadata:meta}).eq("id",i.id).eq("company_id",companyId);if(up.error)return json({ok:false,error:"integration_status_update_failed",details:up.error.message},500);
 return json({ok:true,status:"connected",channel,account:graph,webhook:{url:meta.webhook_url,verify_token:meta.webhook_verify_token}});
}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
